### ISSUE TITLE
Replace containers-ftw with sci-f in all URLs

### ISSUE THREAD

**Issue by julianpistorius** [containers-ftw/apps#31]
There are a number of links pointing to https://containers-ftw.github.io which no longer work. I assume the main URL was changed at some point, and a few places were missed.

For example on the masthead of the GitHub repo:

![Screen Shot 2020-04-10 at 09 15 51](https://user-images.githubusercontent.com/742633/79005980-9de2c380-7b47-11ea-9970-79400b21275d.png)

And in the generated `index.json` file for the apps API (https://sci-f.github.io/apps/api/index.json):

![Screen Shot 2020-04-10 at 09 17 39](https://user-images.githubusercontent.com/742633/79005981-9fac8700-7b47-11ea-87a5-dfdd8dd2f8ff.png)

Searching for "containers-ftw" in the organization shows following occurrences in code:

https://github.com/search?q=org%3Asci-f+%22containers-ftw%22&type=Code

I'm happy to help fix this, and creating this issue so I don't forget.

**Comment by vsoch** [comment]
Thanks for opening this issue @julianpistorius ! The funny thing is that I think those pages were rendered using site.baseurl, which means that the github organization was changed after the last rendering (and it hasn't been updated since!). I think there are a fair number of users that take advantage of SCIF for multiple entrypoints / environments in a single container, but the "apps" idea here (or sharing of them) never took off. I'm okay with that :)

**Comment by julianpistorius** [comment]
My pleasure @vsoch. 

I really like the app idea. Do you know why it did not take off? Do you know of other tools which researchers use to achieve the same thing?

**Comment by vsoch** [comment]
Ah, I think that's one I can answer! Taking the recipes (or any kind of work for that matter) and going out of one's way to document or preserve metadata never really works if the researcher doesn't have a natural incentive to do so (e.g., some requirement for publishing). I implemented a parsing of apps in Singularity Hub, but I don't think it's hugely used and probably is an extra feature that should have been removed.
